### ISSUE TITLE
Integration with phpro/soap-client

### ISSUE THREAD

**Issue by freezysko** [freshcells/soap-client-bundle#12]
Hi
what do you think about replacing ext-soap dependency with https://github.com/phpro/soap-client ?
It will bring many new features which can be handy

**Comment by ivoba** [comment]
Hi,
i have no experience so far with phpro/soap-client but i guess its a good replacement.

However its probably a rather bigger rewrite and we currently dont plan to do so.

If anyone is willing to make a PR i would welcome this.

**Comment by ivoba** [comment]
So i checked phpro/soap-client and i guess we should use a new bundle for this, like f.e. fix and upgrade https://github.com/phpro/soap-client-sf2-bridge.

Integrating it here is too much i guess.
