### ISSUE TITLE
Local WSDL location not used, file location instead 

### ISSUE THREAD

**Issue by pdoreau** [freshcells/soap-client-bundle#16]
In order to avoid a network request during build / test phase, I copied locally the wsdl of the service I want to request.
I use the mocking feature and everything is fine for building / testing.
However, the location of the service is set to the local wsdl file, causing an "Unable to parse URL" error for dev/prod env.

Is there a better way to avoid the wsdl network request at build / test stage ?
Is it possible to use the url detected in the wsdl as service location (expected behaviour isn't it) ?

**Comment by ivoba** [comment]
Local WSDL should work when passed into constructor:

    $wsdl = './tests/fixtures/Wsdl/test.wsdl'
    $client = new \Freshcells\SoapClientBundle\SoapClient\SoapClient($wsdl, array_merge($defaults, $options));


In WSDL relative pathes to main test.wsdl also should work:

    <include schemaLocation="./test?xsd=46"/>

Do you have an example?

**Comment by pdoreau** [comment]
Sure :
```
$client = new \Freshcells\SoapClientBundle\SoapClient\SoapClient('/app/dilbert.asmx.xml');

try {
      $client->DailyDilbert();
} catch (\Exception $e) {
       echo $e->getMessage();
}
```
Note: the file exists (downloaded from http://gcomputer.net/webservices/dilbert.asmx?WSDL).

Result :

`Unable to parse URL`

**Comment by ivoba** [comment]
@pdoreau I added a demo test with a local wsdl.

The trick is to add the location to the options, when using a local wsdl.
Unfortunatly the PHP SoapClient does not resolve this just from the wsdl.

```
    $client = new \Freshcells\SoapClientBundle\SoapClient\SoapClient(
       '/app/dilbert.asmx.xml', 
       ['location: 'http://gcomputer.net/webservices/dilbert.asmx'']
     );
```

**Comment by pdoreau** [comment]
@ivoba the native php SoapClient resolves location from wsdl doesn't it ?

Freshcells SoapClient class defines the location option if wsdl is defined :

```
        if (!is_null($wsdl)) {
            // if option 'location' not set explicit use WSDL URL as service location
            if (!isset($options['location'])) {
                $options['location'] = $this->resolveLocation($wsdl);
            }
        }
```
So I made it resolve from wsdl by setting location to null before usage :
`$client->__setLocation();

**Comment by REBELinBLUE** [comment]
I had this question, why is the location being set when using a WSDL? The PHP client gets it from `<soap:address location="" />` in the WSDL doesn't it? In another implementation just using the SoapClient directly it appears to be doing so, and the PHP Documentation says this option only needs to be set in non-WSDL node.

Obviously I can just explicitly set it in the options but I am just wondering why the bundle calculates it from the WSDL URL when it shouldn't need to?

https://www.php.net/manual/en/soapclient.setlocation.php also says it uses the endpoint URL from the WSDL file by default

**Comment by ivoba** [comment]
@pdoreau @REBELinBLUE 
Well i cant recall the reason for calculating the location. 
Probably some legacy workaround for faulty Wsdl.

I will remove this.

**Comment by REBELinBLUE** [comment]
Thanks, I assumed it was either something I was missing or for a bug in a very specific PHP version. Instead of completely removing it, what about just checking that `$wsdl` begins with `http` before using it to calculate the location? Very useful little bundle though, so thanks :)

**Comment by ivoba** [comment]
@REBELinBLUE i added the http check.
Thanks.

If its ok ill make a new patch release.
