### ISSUE TITLE
Features: Interface and Options getter method

### ISSUE THREAD

**Issue by llaville** [freshcells/soap-client-bundle#2]
Hello,

Thanks for you bundle, that I used since few days now. I like it but I think there are at least two features missing.

**First**: Interface that should define the class, and be used for Dependency Injection rather than concrete class instance.

**Second**:  a new getter method to retrieve all Soap Client options  

Waiting for reply to know your point of view !
Thanks in advance
Laurent

**Comment by ivoba** [comment]
Hi, 
thanks for your suggestions.
Feel free to send in a PR per feature.

Did you mean a Interface for the SoapClient class?

**Comment by llaville** [comment]
Hi.
A interface for your class that extends the native SoapClient, because it did not provide itself an interface.
Ok i will do the PR this day.

**Comment by llaville** [comment]
Now the first part was accepted, I'll open in next hours a new PR corresponding to  the getter options.

Thanks to have merged the first part !

**Comment by llaville** [comment]
And to conclude my features request the new PR is available #5

**Comment by ivoba** [comment]
PR is merged, thx
