### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by REBELinBLUE** [freshcells/soap-client-bundle#21]
Are you planning to support PHP 8? From what I can see the only thing stopping it from installing on PHP 8 is

https://github.com/freshcells/soap-client-bundle/blob/main/composer.json#L27

needs to be

```"php": "^7.4 || ^8.0",```

from what I can see, everything else should work fine

**Comment by ivoba** [comment]
@REBELinBLUE I added PHP8 but tests fail: https://github.com/freshcells/soap-client-bundle/runs/3399957958?check_suite_focus=true

I will try to fix this later, also PRs are welcome.

**Comment by REBELinBLUE** [comment]
One of our developers at work is gonna have a try and will submit a PR. Thanks

**Comment by stuartwilsondev** [comment]
👋  

I submitted https://github.com/freshcells/soap-client-bundle/pull/22. Tests look ok but it's failing on uploading the coverage files 

It looks like the phar file is not directly supported 
https://github.com/scrutinizer-ci/ocular/issues/54#issuecomment-784993370

**Comment by ivoba** [comment]
@stuartwilsondev yes the phar is incomatible with PHP8. I will move this to a PHP7.4 build.
PR looks good, will merge.
