### ISSUE TITLE
Can't install on Syfmony 5.4.4

### ISSUE THREAD

**Issue by alexain** [freshcells/soap-client-bundle#24]
On a fresh installation of Symfony 5.4.4 with PHP 8.1.3 and latest version of Composer and Symfony CLI, it can't install with this problems:

Problem 1
    - Root composer.json requires freshcells/soap-client-bundle ^2.2 -> satisfiable by freshcells/soap-client-bundle[2.2.0].
    - freshcells/soap-client-bundle 2.2.0 requires psr/log ^1.1 -> found psr/log[1.1.0, ..., 1.1.4] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by alexain** [comment]
If I install with -W option, it is installed correctly but downgrade PSR/log from 2.0.0 to 1.1.4

**Comment by ivoba** [comment]
Fixed in version 2.2.1
