### ISSUE TITLE
return type exception in PHP8.1

### ISSUE THREAD

**Issue by Lappihuan** [freshcells/soap-client-bundle#26]
We get this Exception in PHP8.1 on every request:
`Deprecated: Return type of Freshcells\SoapClientBundle\SoapClient\SoapClient::__soapCall($function_name, $arguments, $options = null, $input_headers = null, &$output_headers = null) should either be compatible with SoapClient::__soapCall(string $name, array $args, ?array $options = null, $inputHeaders = null, &$outputHeaders = null): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice`

seems like its just missing `mixed` as return type declaration.

**Comment by ivoba** [comment]
Adding :mixed return type is PHP 8.1 only.
So this would be part of next major version where PHP 8.1 is minimum version.

**Comment by Lappihuan** [comment]
I guess it would be fine to add `#[\ReturnTypeWillChange]` attribute for now.

**Comment by ivoba** [comment]
@Lappihuan added to main. Can you check if this works.

**Comment by Lappihuan** [comment]
@ivoba using `dev-main` i get all of these deprecation errors:
`Return type of  Freshcells\SoapClientBundle\SoapClient\SoapClient::__call($function_name,  $arguments) should either be compatible with SoapClient::__call(string  $name, array $args): mixed, or the #[\ReturnTypeWillChange] attribute  should be used to temporarily suppress the notice`

`Return type of Freshcells\SoapClientBundle\SoapClient\SoapClient::__soapCall($function_name, $arguments, $options = null, $input_headers = null, &$output_headers = null) should either be compatible with SoapClient::__soapCall(string $name, array $args, ?array $options = null, $inputHeaders = null, &$outputHeaders = null): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice`

`Return type of Freshcells\SoapClientBundle\SoapClient\SoapClient::__doRequest($request, $location, $action, $version, $one_way = null) should either be compatible with SoapClient::__doRequest(string $request, string $location, string $action, int $version, bool $oneWay = false): ?string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice`

`Method "SoapClient::__call()" might add "mixed" as a native return type declaration in the future. Do the same in child class "Freshcells\SoapClientBundle\SoapClient\SoapClient" now to avoid errors or add an explicit @return annotation to suppress this message.`

`Method "SoapClient::__soapCall()" might add "mixed" as a native return type declaration in the future. Do the same in child class "Freshcells\SoapClientBundle\SoapClient\SoapClient" now to avoid errors or add an explicit @return annotation to suppress this message.`

hmm, this almost feels like it did not update, let me recheck

**Comment by Lappihuan** [comment]
@ivoba ignore my list of errors above, this is what i actually get with dev-main:

Seems like `__doRequest` also needs the attribute:
`Return type of Freshcells\SoapClientBundle\SoapClient\SoapClient::__doRequest($request, $location, $action, $version, $one_way = null) should either be compatible with SoapClient::__doRequest(string $request, string $location, string $action, int $version, bool $oneWay = false): ?string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice`

What confuses me is that i now have these erros: 
`Method "SoapClient::__call()" might add "mixed" as a native return type declaration in the future. Do the same in child class "Freshcells\SoapClientBundle\SoapClient\SoapClient" now to avoid errors or add an explicit @return annotation to suppress this message.`

`Method "SoapClient::__soapCall()" might add "mixed" as a native return type declaration in the future. Do the same in child class "Freshcells\SoapClientBundle\SoapClient\SoapClient" now to avoid errors or add an explicit @return annotation to suppress this message.`

I would have expected `#[\ReturnTypeWillChange]` to completly supress the issue.

**Comment by ivoba** [comment]
@Lappihuan i added an explicit @return annotation as the message suggested. Does this help?

**Comment by Lappihuan** [comment]
@ivoba thanks! now all exceptions are gone :+1:

**Comment by ivoba** [comment]
Released as 2.3.1.
