### ISSUE TITLE
Exception in preCall functions

### ISSUE THREAD

**Issue by alexain** [freshcells/soap-client-bundle#6]
Every Soap call, it return me this exception:

> Argument 2 passed to Freshcells\SoapClientBundle\SoapClient\SoapClient::preCall() must be of the type string, null given, called in /Users/a.capano/Developing/biosfera/vendor/freshcells/soap-client-bundle/src/SoapClient/SoapClient.php on line 138

I've to modify manually the doRequest function at line 138, adding an if statement line before:
`if ($action == null) $action = '';`
`$this->preCall($id->toString(), $action = '', $request);`

Can you add this? Or can I submit a commit to add the line?

**Comment by ivoba** [comment]
@Alexain i added a fix. Can you check if this works for you.
