### ISSUE TITLE
null Response throws Exception

### ISSUE THREAD

**Issue by fyrye** [freshcells/soap-client-bundle#7]
Effectively I have a temperamental service that is refusing to send back a response string.
Instead I am receiving `[freshcells/soap-client-bundle] fault "Argument 3 passed to Freshcells\SoapClientBundle\Event\ResponseEvent::__construct() must be of the type string, null given` which is forcing me to use 

```php
try{
    $this->response = $this->client->wsdlMethod($config);
} catch(\Throwable $e) {
   $this->response = $e->getMessage();
}
```

Looking at the `ResponseEvent` the default values are `null`, but are type hinted as `string`.

Thoughts on accepting `?string $response = null` to allow for the developers who use your library to handle the null response, or changing the exception to a more specific one, like `NullResponseException`?

**Comment by ivoba** [comment]
@fyrye I made the arguments nullable. Can you check if this works for you.

**Comment by fyrye** [comment]
Thanks!  @ivoba 
My project uses stable versions, once it gets tagged as stable, I will try it out.

**Comment by ivoba** [comment]
@fyrye is tagged as 1.4.0.
Normally one would try it out before a release gets stable, but i guess it will work.
